### ISSUE TITLE
Can Not Save option to open in new tab

### ISSUE THREAD

**Issue by GRamirez2** [adeekshith/Docs-Online-Viewer#54]
When I go to the extension options -> general. I can not save the option to open in a new tab, it always go back to unchecked.

**Comment by vinkcshape** [comment]
Original comment about this issue was on Dec 12th, 2022.  Still broke as of March 30th, 2023.

**Comment by noobb64** [comment]
Same issue. Save button doesn't work.

**Comment by adeekshith** [comment]
Hi folks, I finally got to it and fixed the issue here along with migrating to the latest Manifest V3: https://github.com/adeekshith/Docs-Online-Viewer/pull/60

I'd be great if any of you can review or give me feedback. Thanks!
